-- "user"는 예약어일 수 있으므로 큰따옴표로 감쌉니다.
create table "user"
(
    idx                      bigint generated by default as identity primary key,
    username                 varchar(50) not null,
    password                 varchar(100) not null,
    role                     varchar(15) default 'personal' not null,
    is_ban                   tinyint default 0 not null,
    personal_name            varchar(30) null,
    personal_brith           date null,
    enterprise_name          varchar(20) null,
    enterprise_nation_code   varchar(5) null,
    enterprise_province_code varchar(10) null,
    created_at               timestamp not null,
    updated_at               timestamp not null,
    deleted_at               timestamp null
);

-- 컬럼 코멘트 추가
comment on column "user".personal_name is '실명';
comment on column "user".personal_brith is '개인 - 생년월일';

create table job_posting
(
    idx              bigint generated by default as identity primary key,
    company_id       bigint null,
    recruit_reward   int default 0 not null,
    recruit_position varchar(30) not null,
    description      text not null,
    required_skill   varchar(20) not null,
    created_at       timestamp not null,
    updated_at       timestamp not null,
    deleted_at       timestamp null,
    constraint job_posting_user_idx_fk foreign key (company_id) references "user"(idx)
);

-- job_posting 테이블의 컬럼 및 테이블 코멘트 추가
comment on column job_posting.recruit_reward is '채용 보상금';
comment on column job_posting.recruit_position is '채용 포지션';
comment on column job_posting.description is '채용 내용';
comment on column job_posting.created_at is '삭';
comment on table job_posting is '채용 공고';

-- 인덱스 생성
create index job_posting_idx_index on job_posting (idx);
create index user_idx_index on "user" (idx);
